# Generated by Django 3.0.6 on 2020-05-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executivetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_digest',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='connection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='executivetable.Connection'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='startup_receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_receiver_id', to='executivetable.Startup'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='startup_sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_sender_id', to='executivetable.Startup'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='user_receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver_id', to='executivetable.User'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='user_sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender_id', to='executivetable.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='startup_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='executivetable.Startup'),
        ),
    ]
